
package pt.uac.cafeteria.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;

/**
 * 
 * Represents the Front Office user interface.
 */
public class Frontend extends javax.swing.JFrame {

    private static int year = Calendar.getInstance().get(Calendar.YEAR);
    private static int month = Calendar.getInstance().get(Calendar.MONTH) + 1;
    private static int day = Calendar.getInstance().get(Calendar.DATE);
    
    /** Creates new form Frontend */
    public Frontend() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screenSize.width/2 - 400, screenSize.height/2 - 300);
        
        menuPanel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTime = new javax.swing.ButtonGroup();
        bgDish = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        lblNumber = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        lblPinCode = new javax.swing.JLabel();
        pinCode = new javax.swing.JPasswordField();
        confirm = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        lblFrontBK = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        panelButtons = new javax.swing.JPanel();
        btnBuyTicket = new javax.swing.JButton();
        btnCheckBalance = new javax.swing.JButton();
        btnChangePinCode = new javax.swing.JButton();
        btnChangeEmail = new javax.swing.JButton();
        btnTerminate = new javax.swing.JButton();
        panelWelcome = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        lblWelcome2 = new javax.swing.JLabel();
        lblWelcome3 = new javax.swing.JLabel();
        panelBuyTicket = new javax.swing.JPanel();
        ifWarning = new javax.swing.JInternalFrame();
        lblMoreTickets1 = new javax.swing.JLabel();
        btnYesCancel = new javax.swing.JButton();
        btnNoCancel = new javax.swing.JButton();
        ifTickets = new javax.swing.JInternalFrame();
        lblMoreTickets2 = new javax.swing.JLabel();
        btnYesTickets = new javax.swing.JButton();
        btnNoTickets = new javax.swing.JButton();
        ifPurchaseSuccess = new javax.swing.JInternalFrame();
        lblPurchaseSuccess = new javax.swing.JLabel();
        btnPurchaseOk = new javax.swing.JButton();
        spSummary = new javax.swing.JScrollPane();
        panelSummary = new javax.swing.JPanel();
        lblPurchaseDate = new javax.swing.JLabel();
        lblPurchaseDateText = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblPriceText = new javax.swing.JLabel();
        lpMeal1 = new javax.swing.JLayeredPane();
        lblTicketMealDate = new javax.swing.JLabel();
        lblTicketMealTime = new javax.swing.JLabel();
        lblTicketSoup = new javax.swing.JLabel();
        lblTicketDish = new javax.swing.JLabel();
        lblTicketDessert = new javax.swing.JLabel();
        lblTicketMealDateText = new javax.swing.JLabel();
        lbTicketlMealTimeText = new javax.swing.JLabel();
        lblTicketSoupText = new javax.swing.JLabel();
        lblTicketDishText = new javax.swing.JLabel();
        lblTicketDessertText = new javax.swing.JLabel();
        panelChooseDay = new javax.swing.JPanel();
        cbYearChoice = new javax.swing.JComboBox();
        cbMonthChoice = new javax.swing.JComboBox();
        cbDayChoice = new javax.swing.JComboBox();
        rbLunch = new javax.swing.JRadioButton();
        rbDinner = new javax.swing.JRadioButton();
        panelShowMeal = new javax.swing.JPanel();
        lblChooseDish = new javax.swing.JLabel();
        rbMeat = new javax.swing.JRadioButton();
        rbFish = new javax.swing.JRadioButton();
        rbVegetarian = new javax.swing.JRadioButton();
        lblSoup = new javax.swing.JLabel();
        lblMeat = new javax.swing.JLabel();
        lblFish = new javax.swing.JLabel();
        lblVegetarian = new javax.swing.JLabel();
        lblDessert = new javax.swing.JLabel();
        lblSoupText = new javax.swing.JLabel();
        lblMeatText = new javax.swing.JLabel();
        lblFishText = new javax.swing.JLabel();
        lblVegetarianText = new javax.swing.JLabel();
        lblDessertText = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        btnConfirmMeal = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        panelCheckBalance = new javax.swing.JPanel();
        panelStudent = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblScholarship = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblNameText = new javax.swing.JLabel();
        lblAddressText = new javax.swing.JLabel();
        lblPhoneText = new javax.swing.JLabel();
        lblEmailText = new javax.swing.JLabel();
        chbScholarship = new javax.swing.JCheckBox();
        lblCourseText = new javax.swing.JLabel();
        panelAccount = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        lblAccountText = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblBalanceText = new javax.swing.JLabel();
        panelMovements = new javax.swing.JPanel();
        spMovements = new javax.swing.JScrollPane();
        lisDates = new javax.swing.JList();
        panelChangePinCode = new javax.swing.JPanel();
        ifChangePinCodeSuccess = new javax.swing.JInternalFrame();
        lblChangePinCodeSuccess1 = new javax.swing.JLabel();
        lblChangePinCodeSuccess2 = new javax.swing.JLabel();
        btnChangePinCodeSuccessOk = new javax.swing.JButton();
        panelChangePinCodeFields = new javax.swing.JPanel();
        lblCurrentPin = new javax.swing.JLabel();
        lblNewPin = new javax.swing.JLabel();
        lblConfiirmPin = new javax.swing.JLabel();
        pfCurrentPin = new javax.swing.JPasswordField();
        pfNewPin = new javax.swing.JPasswordField();
        pfConfirmPin = new javax.swing.JPasswordField();
        btnValidatePinCode = new javax.swing.JButton();
        btnCancelNewPinCode = new javax.swing.JButton();
        panelChangeEmail = new javax.swing.JPanel();
        ifChangeEmailSuccess = new javax.swing.JInternalFrame();
        lblChangeEmailSuccess = new javax.swing.JLabel();
        btnChangeEmailOk = new javax.swing.JButton();
        panelChangeEmailFields = new javax.swing.JPanel();
        lblCurrentEmail = new javax.swing.JLabel();
        lblNewEmail = new javax.swing.JLabel();
        lblCurrentEmailText = new javax.swing.JLabel();
        tfNewMailText = new javax.swing.JTextField();
        btnValidateEmail = new javax.swing.JButton();
        btnCancelNewEmail = new javax.swing.JButton();
        lblLogo1 = new javax.swing.JLabel();
        lblFrontBK1 = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafeteria");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setLayout(null);

        lblNumber.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblNumber.setText("Número de Conta");
        mainPanel.add(lblNumber);
        lblNumber.setBounds(355, 150, 110, 14);

        number.setFont(new java.awt.Font("Tahoma", 1, 11));
        number.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mainPanel.add(number);
        number.setBounds(350, 170, 110, 30);

        lblPinCode.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblPinCode.setText("Código de Acesso");
        mainPanel.add(lblPinCode);
        lblPinCode.setBounds(355, 240, 110, 14);
        mainPanel.add(pinCode);
        pinCode.setBounds(350, 265, 110, 30);

        confirm.setText("Confirmar");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                confirmMouseReleased(evt);
            }
        });
        mainPanel.add(confirm);
        confirm.setBounds(360, 343, 90, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/uac/cafeteria/ui/images/logo.png"))); // NOI18N
        mainPanel.add(logo);
        logo.setBounds(355, 390, 100, 100);

        lblFrontBK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/uac/cafeteria/ui/images/frontBK.png"))); // NOI18N
        mainPanel.add(lblFrontBK);
        lblFrontBK.setBounds(0, 0, 939, 683);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        mainPanel.add(loginPanel);
        loginPanel.setBounds(300, 100, 200, 400);

        menuPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        menuPanel.setLayout(null);

        panelButtons.setOpaque(false);

        btnBuyTicket.setText("Comprar Senha");
        btnBuyTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuyTicketMouseReleased(evt);
            }
        });

        btnCheckBalance.setText("Consultar Saldo");
        btnCheckBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCheckBalanceMouseReleased(evt);
            }
        });

        btnChangePinCode.setText("Alterar Código de Acesso");
        btnChangePinCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangePinCodeMouseReleased(evt);
            }
        });

        btnChangeEmail.setText("Alterar e-mail");
        btnChangeEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangeEmailMouseReleased(evt);
            }
        });

        btnTerminate.setText("Terminar");
        btnTerminate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTerminateMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuyTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(btnCheckBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(btnChangePinCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(btnTerminate, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBuyTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnCheckBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnChangePinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChangeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307)
                .addComponent(btnTerminate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        menuPanel.add(panelButtons);
        panelButtons.setBounds(0, 0, 200, 600);

        panelWelcome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bem-Vindo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Aplicação para a compra de senhas da");

        lblWelcome1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("Universidade dos Açores");

        lblWelcome2.setText("- Escolha uma das operações disponíveis.");

        lblWelcome3.setText("- Quando concluir as suas operações, pressione o botão Terminar.");

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(lblWelcome2)
                    .addComponent(lblWelcome3))
                .addContainerGap())
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome1)
                .addGap(33, 33, 33)
                .addComponent(lblWelcome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcome3)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        menuPanel.add(panelWelcome);
        panelWelcome.setBounds(250, 25, 440, 200);

        panelBuyTicket.setOpaque(false);
        panelBuyTicket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ifWarning.setTitle("Aviso");
        ifWarning.setVisible(true);

        lblMoreTickets1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMoreTickets1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMoreTickets1.setText("Tem a certeza que quer Cancelar?");

        btnYesCancel.setText("Sim");
        btnYesCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnYesCancelMouseReleased(evt);
            }
        });

        btnNoCancel.setText("Não");
        btnNoCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNoCancelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ifWarningLayout = new javax.swing.GroupLayout(ifWarning.getContentPane());
        ifWarning.getContentPane().setLayout(ifWarningLayout);
        ifWarningLayout.setHorizontalGroup(
            ifWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifWarningLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(btnYesCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNoCancel)
                .addGap(43, 43, 43))
            .addComponent(lblMoreTickets1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        ifWarningLayout.setVerticalGroup(
            ifWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifWarningLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblMoreTickets1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ifWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoCancel)
                    .addComponent(btnYesCancel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelBuyTicket.add(ifWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 160));

        ifTickets.setTitle("Informação");
        ifTickets.setVisible(true);

        lblMoreTickets2.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMoreTickets2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMoreTickets2.setText("Deseja adquirir mais senhas?");

        btnYesTickets.setText("Sim");
        btnYesTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnYesTicketsMouseReleased(evt);
            }
        });

        btnNoTickets.setText("Não");
        btnNoTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNoTicketsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ifTicketsLayout = new javax.swing.GroupLayout(ifTickets.getContentPane());
        ifTickets.getContentPane().setLayout(ifTicketsLayout);
        ifTicketsLayout.setHorizontalGroup(
            ifTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifTicketsLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(btnYesTickets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNoTickets)
                .addGap(45, 45, 45))
            .addComponent(lblMoreTickets2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        ifTicketsLayout.setVerticalGroup(
            ifTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ifTicketsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblMoreTickets2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(ifTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoTickets)
                    .addComponent(btnYesTickets))
                .addGap(20, 20, 20))
        );

        panelBuyTicket.add(ifTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 160));

        ifPurchaseSuccess.setTitle("Informação");
        ifPurchaseSuccess.setVisible(true);

        lblPurchaseSuccess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPurchaseSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPurchaseSuccess.setText("Compra efectuada com sucesso!");

        btnPurchaseOk.setText("OK");
        btnPurchaseOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPurchaseOkMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ifPurchaseSuccessLayout = new javax.swing.GroupLayout(ifPurchaseSuccess.getContentPane());
        ifPurchaseSuccess.getContentPane().setLayout(ifPurchaseSuccessLayout);
        ifPurchaseSuccessLayout.setHorizontalGroup(
            ifPurchaseSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPurchaseSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addGroup(ifPurchaseSuccessLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnPurchaseOk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        ifPurchaseSuccessLayout.setVerticalGroup(
            ifPurchaseSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifPurchaseSuccessLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPurchaseSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPurchaseOk)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelBuyTicket.add(ifPurchaseSuccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 160));

        spSummary.setBorder(null);
        spSummary.setToolTipText("");
        spSummary.setPreferredSize(new java.awt.Dimension(560, 350));

        panelSummary.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        panelSummary.setOpaque(false);
        panelSummary.setPreferredSize(new java.awt.Dimension(300, 270));

        lblPurchaseDate.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblPurchaseDate.setText("Data da Compra:");

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblPrice.setText("Preço Total:");

        lblPriceText.setText("3€");

        lpMeal1.setBackground(new java.awt.Color(102, 102, 102));
        lpMeal1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblTicketMealDate.setText("Data:");
        lblTicketMealDate.setBounds(10, 10, 50, 20);
        lpMeal1.add(lblTicketMealDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketMealTime.setText("Refeição");
        lblTicketMealTime.setBounds(10, 40, 70, 20);
        lpMeal1.add(lblTicketMealTime, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketSoup.setText("Sopa:");
        lblTicketSoup.setBounds(10, 70, 60, 20);
        lpMeal1.add(lblTicketSoup, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketDish.setText("Carne:");
        lblTicketDish.setBounds(10, 100, 50, 20);
        lpMeal1.add(lblTicketDish, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketDessert.setText("Sobremesa:");
        lblTicketDessert.setBounds(10, 130, 80, 20);
        lpMeal1.add(lblTicketDessert, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketMealDateText.setText("10/1/2012");
        lblTicketMealDateText.setBounds(100, 10, 70, 20);
        lpMeal1.add(lblTicketMealDateText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbTicketlMealTimeText.setText("Almoço");
        lbTicketlMealTimeText.setBounds(100, 40, 170, 20);
        lpMeal1.add(lbTicketlMealTimeText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketSoupText.setText("Caldo Verde");
        lblTicketSoupText.setBounds(100, 70, 300, 20);
        lpMeal1.add(lblTicketSoupText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketDishText.setText("Bifes");
        lblTicketDishText.setBounds(100, 100, 300, 20);
        lpMeal1.add(lblTicketDishText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblTicketDessertText.setText("Mousse");
        lblTicketDessertText.setBounds(100, 130, 300, 20);
        lpMeal1.add(lblTicketDessertText, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelSummaryLayout = new javax.swing.GroupLayout(panelSummary);
        panelSummary.setLayout(panelSummaryLayout);
        panelSummaryLayout.setHorizontalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSummaryLayout.createSequentialGroup()
                        .addComponent(lblPurchaseDate)
                        .addGap(10, 10, 10)
                        .addComponent(lblPurchaseDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(panelSummaryLayout.createSequentialGroup()
                        .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(lblPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(371, 371, 371))
                    .addGroup(panelSummaryLayout.createSequentialGroup()
                        .addComponent(lpMeal1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelSummaryLayout.setVerticalGroup(
            panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPurchaseDateText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lpMeal1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        spSummary.setViewportView(panelSummary);

        panelBuyTicket.add(spSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 300));

        panelChooseDay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escolha a data e a refeição", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        panelChooseDay.setMinimumSize(new java.awt.Dimension(400, 400));
        panelChooseDay.setPreferredSize(new java.awt.Dimension(333, 155));
        panelChooseDay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbYearChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        panelChooseDay.add(cbYearChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        cbMonthChoice.setMaximumRowCount(12);
        cbMonthChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        panelChooseDay.add(cbMonthChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        cbDayChoice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelChooseDay.add(cbDayChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        bgTime.add(rbLunch);
        rbLunch.setText("Almoço");
        rbLunch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbLunchMouseReleased(evt);
            }
        });
        panelChooseDay.add(rbLunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        bgTime.add(rbDinner);
        rbDinner.setText("Jantar");
        rbDinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbDinnerMouseReleased(evt);
            }
        });
        panelChooseDay.add(rbDinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        panelBuyTicket.add(panelChooseDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        panelShowMeal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));
        panelShowMeal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChooseDish.setText("Faça a sua escolha:");
        panelShowMeal.add(lblChooseDish, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        bgDish.add(rbMeat);
        rbMeat.setText("Carne");
        rbMeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbMeatMouseReleased(evt);
            }
        });
        panelShowMeal.add(rbMeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        bgDish.add(rbFish);
        rbFish.setText("Peixe");
        panelShowMeal.add(rbFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        bgDish.add(rbVegetarian);
        rbVegetarian.setText("Vegetariano");
        panelShowMeal.add(rbVegetarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        lblSoup.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblSoup.setText("Sopa:");
        panelShowMeal.add(lblSoup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        lblMeat.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMeat.setText("Carne:");
        panelShowMeal.add(lblMeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        lblFish.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblFish.setText("Peixe:");
        panelShowMeal.add(lblFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        lblVegetarian.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblVegetarian.setText("Vegetariano:");
        panelShowMeal.add(lblVegetarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        lblDessert.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDessert.setText("Sobremesa:");
        panelShowMeal.add(lblDessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));
        panelShowMeal.add(lblSoupText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, 20));
        panelShowMeal.add(lblMeatText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 290, 20));
        panelShowMeal.add(lblFishText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 290, 20));
        panelShowMeal.add(lblVegetarianText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, 20));
        panelShowMeal.add(lblDessertText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 290, 20));

        panelBuyTicket.add(panelShowMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 440, 260));

        btnBuy.setText("Comprar");
        btnBuy.setPreferredSize(new java.awt.Dimension(75, 23));
        btnBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuyMouseReleased(evt);
            }
        });
        panelBuyTicket.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 80, 30));

        btnConfirmMeal.setText("OK");
        btnConfirmMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnConfirmMealMouseReleased(evt);
            }
        });
        panelBuyTicket.add(btnConfirmMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 80, 30));

        btnCancel.setText("Cancelar");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });
        panelBuyTicket.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 80, 30));

        menuPanel.add(panelBuyTicket);
        panelBuyTicket.setBounds(250, 25, 440, 520);

        panelCheckBalance.setOpaque(false);
        panelCheckBalance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelStudent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aluno", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        lblName.setText("Nome:");

        lblAddress.setText("Rua:");

        lblPhone.setText("Telefone:");

        lblEmail.setText("Email:");

        lblScholarship.setText("Bolseiro:");

        lblCourse.setText("Curso:");

        lblNameText.setText("Paulo Dinis Vieira Silva");

        lblAddressText.setText("Rua Torta, nº2");

        lblPhoneText.setText("296123123");

        lblEmailText.setText("20081234@alunos.uac.pt");

        chbScholarship.setSelected(true);
        chbScholarship.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbScholarship.setEnabled(false);

        lblCourseText.setText("Informática - Redes e Multimédia");

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblAddress)
                    .addComponent(lblPhone)
                    .addComponent(lblEmail)
                    .addComponent(lblScholarship)
                    .addComponent(lblCourse))
                .addGap(21, 21, 21)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailText)
                    .addComponent(lblPhoneText)
                    .addComponent(lblAddressText)
                    .addComponent(lblNameText)
                    .addComponent(lblCourseText)
                    .addComponent(chbScholarship))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScholarship, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbScholarship))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCheckBalance.add(panelStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 210));

        panelAccount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimentos de Conta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblAccount.setText("Conta: ");

        lblAccountText.setText("20081234");

        lblBalance.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblBalance.setText("Saldo:");

        lblBalanceText.setText("100€");

        panelMovements.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lisDates.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "01/2/2011     Compra     6€", "02/2/2011     Compra     3€", "02/2/2011     Débito     10€", "03/2/2011     Compra     3€" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lisDates.setOpaque(false);
        spMovements.setViewportView(lisDates);

        javax.swing.GroupLayout panelMovementsLayout = new javax.swing.GroupLayout(panelMovements);
        panelMovements.setLayout(panelMovementsLayout);
        panelMovementsLayout.setHorizontalGroup(
            panelMovementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMovements, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMovementsLayout.setVerticalGroup(
            panelMovementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMovements, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAccountLayout = new javax.swing.GroupLayout(panelAccount);
        panelAccount.setLayout(panelAccountLayout);
        panelAccountLayout.setHorizontalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addComponent(panelMovements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelAccountLayout.createSequentialGroup()
                        .addComponent(lblAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAccountText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(lblBalance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBalanceText)
                        .addGap(69, 69, 69))))
        );
        panelAccountLayout.setVerticalGroup(
            panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccount)
                    .addComponent(lblAccountText)
                    .addComponent(lblBalance)
                    .addComponent(lblBalanceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMovements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCheckBalance.add(panelAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 440, 290));

        menuPanel.add(panelCheckBalance);
        panelCheckBalance.setBounds(250, 25, 440, 522);

        panelChangePinCode.setMinimumSize(new java.awt.Dimension(440, 520));
        panelChangePinCode.setOpaque(false);
        panelChangePinCode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ifChangePinCodeSuccess.setTitle("Informação");
        ifChangePinCodeSuccess.setVisible(true);

        lblChangePinCodeSuccess1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblChangePinCodeSuccess1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangePinCodeSuccess1.setText("Código de acesso");

        lblChangePinCodeSuccess2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblChangePinCodeSuccess2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangePinCodeSuccess2.setText("alterado com sucesso!");

        btnChangePinCodeSuccessOk.setText("OK");
        btnChangePinCodeSuccessOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangePinCodeSuccessOkMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ifChangePinCodeSuccessLayout = new javax.swing.GroupLayout(ifChangePinCodeSuccess.getContentPane());
        ifChangePinCodeSuccess.getContentPane().setLayout(ifChangePinCodeSuccessLayout);
        ifChangePinCodeSuccessLayout.setHorizontalGroup(
            ifChangePinCodeSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChangePinCodeSuccess1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(lblChangePinCodeSuccess2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addGroup(ifChangePinCodeSuccessLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnChangePinCodeSuccessOk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        ifChangePinCodeSuccessLayout.setVerticalGroup(
            ifChangePinCodeSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifChangePinCodeSuccessLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblChangePinCodeSuccess1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChangePinCodeSuccess2)
                .addGap(18, 18, 18)
                .addComponent(btnChangePinCodeSuccessOk)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelChangePinCode.add(ifChangePinCodeSuccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 160));

        panelChangePinCodeFields.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Código de Acesso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        lblCurrentPin.setText("Insira o código corrente:");

        lblNewPin.setText("Insira o novo código:");

        lblConfiirmPin.setText("Confirmar novo código:");

        javax.swing.GroupLayout panelChangePinCodeFieldsLayout = new javax.swing.GroupLayout(panelChangePinCodeFields);
        panelChangePinCodeFields.setLayout(panelChangePinCodeFieldsLayout);
        panelChangePinCodeFieldsLayout.setHorizontalGroup(
            panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangePinCodeFieldsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfiirmPin)
                    .addComponent(lblNewPin)
                    .addComponent(lblCurrentPin))
                .addGap(18, 18, 18)
                .addGroup(panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfCurrentPin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNewPin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfConfirmPin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        panelChangePinCodeFieldsLayout.setVerticalGroup(
            panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangePinCodeFieldsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfCurrentPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelChangePinCodeFieldsLayout.createSequentialGroup()
                        .addComponent(lblCurrentPin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNewPin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfNewPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panelChangePinCodeFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfiirmPin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfConfirmPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelChangePinCode.add(panelChangePinCodeFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 210));

        btnValidatePinCode.setText("Alterar");
        btnValidatePinCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnValidatePinCodeMouseReleased(evt);
            }
        });
        panelChangePinCode.add(btnValidatePinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 80, 30));

        btnCancelNewPinCode.setText("Cancelar");
        btnCancelNewPinCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelNewPinCodeMouseReleased(evt);
            }
        });
        panelChangePinCode.add(btnCancelNewPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 80, 30));

        menuPanel.add(panelChangePinCode);
        panelChangePinCode.setBounds(250, 25, 440, 522);

        panelChangeEmail.setOpaque(false);
        panelChangeEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ifChangeEmailSuccess.setTitle("Informação");
        ifChangeEmailSuccess.setVisible(true);

        lblChangeEmailSuccess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblChangeEmailSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangeEmailSuccess.setText("Email alterado com sucesso!");

        btnChangeEmailOk.setText("OK");
        btnChangeEmailOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangeEmailOkMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ifChangeEmailSuccessLayout = new javax.swing.GroupLayout(ifChangeEmailSuccess.getContentPane());
        ifChangeEmailSuccess.getContentPane().setLayout(ifChangeEmailSuccessLayout);
        ifChangeEmailSuccessLayout.setHorizontalGroup(
            ifChangeEmailSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
            .addComponent(lblChangeEmailSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addGroup(ifChangeEmailSuccessLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnChangeEmailOk, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        ifChangeEmailSuccessLayout.setVerticalGroup(
            ifChangeEmailSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(ifChangeEmailSuccessLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblChangeEmailSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeEmailOk)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelChangeEmail.add(ifChangeEmailSuccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 160));

        panelChangeEmailFields.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Email", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        lblCurrentEmail.setText("Email corrente:");

        lblNewEmail.setText("Novo email:");

        lblCurrentEmailText.setText("20081234@alunos.uac.pt");

        javax.swing.GroupLayout panelChangeEmailFieldsLayout = new javax.swing.GroupLayout(panelChangeEmailFields);
        panelChangeEmailFields.setLayout(panelChangeEmailFieldsLayout);
        panelChangeEmailFieldsLayout.setHorizontalGroup(
            panelChangeEmailFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeEmailFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChangeEmailFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentEmail)
                    .addComponent(lblNewEmail))
                .addGap(18, 18, 18)
                .addGroup(panelChangeEmailFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNewMailText)
                    .addComponent(lblCurrentEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelChangeEmailFieldsLayout.setVerticalGroup(
            panelChangeEmailFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeEmailFieldsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelChangeEmailFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelChangeEmailFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNewMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        panelChangeEmail.add(panelChangeEmailFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        btnValidateEmail.setText("Alterar");
        btnValidateEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnValidateEmailMouseReleased(evt);
            }
        });
        panelChangeEmail.add(btnValidateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 490, 80, 30));

        btnCancelNewEmail.setText("Cancelar");
        btnCancelNewEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelNewEmailMouseReleased(evt);
            }
        });
        panelChangeEmail.add(btnCancelNewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 490, 80, 30));

        menuPanel.add(panelChangeEmail);
        panelChangeEmail.setBounds(250, 25, 440, 520);

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/uac/cafeteria/ui/images/logo.png"))); // NOI18N
        menuPanel.add(lblLogo1);
        lblLogo1.setBounds(700, 500, 100, 100);

        lblFrontBK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pt/uac/cafeteria/ui/images/frontBK.png"))); // NOI18N
        menuPanel.add(lblFrontBK1);
        lblFrontBK1.setBounds(0, 0, 939, 683);

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        menuPanel.add(separator);
        separator.setBounds(205, 0, 10, 611);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseReleased
        if (confirm.isEnabled()) {
            mainPanel.setVisible(false);
            menuPanel.setVisible(true);
            panelWelcome.setVisible(true);
            panelBuyTicket.setVisible(false);
            panelCheckBalance.setVisible(false);
            panelChangePinCode.setVisible(false);
            panelChangeEmail.setVisible(false);
            panelChooseDay.setVisible(false);
            btnBuyTicket.setEnabled(true);
            btnCheckBalance.setEnabled(true);
            btnChangePinCode.setEnabled(true);
            btnChangeEmail.setEnabled(true);
        }
        
    }//GEN-LAST:event_confirmMouseReleased

    private void btnTerminateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTerminateMouseReleased
        menuPanel.setVisible(false);
        mainPanel.setVisible(true);
    }//GEN-LAST:event_btnTerminateMouseReleased

    private void btnBuyTicketMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyTicketMouseReleased
        if (btnBuyTicket.isEnabled()) {
            panelBuyTicket.setVisible(true);
            panelChooseDay.setVisible(true);
            panelShowMeal.setVisible(false);
            btnConfirmMeal.setVisible(true);
            btnConfirmMeal.setEnabled(false);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            ifTickets.setVisible(false);
            spSummary.setVisible(false);
            btnBuy.setVisible(false);
            bgTime.clearSelection();
            bgDish.clearSelection();
            ifPurchaseSuccess.setVisible(false);
            ifWarning.setVisible(false);
            cbYearChoice.setSelectedIndex(0);
            cbMonthChoice.setSelectedIndex(0);
            cbDayChoice.setSelectedIndex(0);
            btnBuyTicket.setEnabled(false);
            btnCheckBalance.setEnabled(false);
            btnChangePinCode.setEnabled(false);
            btnChangeEmail.setEnabled(false);
            panelWelcome.setVisible(false);
            panelCheckBalance.setVisible(false);
            panelChangePinCode.setVisible(false);
            panelChangeEmail.setVisible(false);
        }
    }//GEN-LAST:event_btnBuyTicketMouseReleased

    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        if (btnCancel.isEnabled()) {
            ifWarning.setVisible(true);
            btnConfirmMeal.setEnabled(false);
            btnBuy.setEnabled(false);
        }
    }//GEN-LAST:event_btnCancelMouseReleased

    private void rbLunchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbLunchMouseReleased
        panelShowMeal.setVisible(true);
        lblSoupText.setText("Caldo Verde");
        lblMeatText.setText("Bifes");
        lblFishText.setText("Chicharros");
        lblVegetarianText.setText("Salada");
        lblDessertText.setText("Mousse");        
    }//GEN-LAST:event_rbLunchMouseReleased

    private void rbMeatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMeatMouseReleased
        btnConfirmMeal.setEnabled(true);
    }//GEN-LAST:event_rbMeatMouseReleased

    private void btnConfirmMealMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMealMouseReleased
        if (btnConfirmMeal.isEnabled()) {
            panelChooseDay.setVisible(false);
            panelShowMeal.setVisible(false);
            spSummary.setVisible(true);
            btnConfirmMeal.setVisible(false);
            btnBuy.setVisible(true);
            btnBuy.setEnabled(true);
            lblPurchaseDateText.setText(""+day+"/"+month+"/"+year);    
        }
    }//GEN-LAST:event_btnConfirmMealMouseReleased

    private void btnYesTicketsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYesTicketsMouseReleased
            ifTickets.setVisible(false);
            spSummary.setVisible(false);
            panelShowMeal.setVisible(false);
            btnBuy.setVisible(false);
            panelChooseDay.setVisible(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            btnConfirmMeal.setVisible(true);
            btnConfirmMeal.setEnabled(false);
            bgTime.clearSelection();
            bgDish.clearSelection();
    }//GEN-LAST:event_btnYesTicketsMouseReleased

    private void btnNoTicketsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoTicketsMouseReleased
        if(btnNoTickets.isEnabled()) {
            ifTickets.setVisible(false);
            btnBuy.setVisible(false);
            btnCancel.setVisible(false);
            btnBuyTicket.setEnabled(true);
            btnCheckBalance.setEnabled(true);
            btnChangePinCode.setEnabled(true);
            btnChangeEmail.setEnabled(true);
            panelWelcome.setVisible(true);
        }
    }//GEN-LAST:event_btnNoTicketsMouseReleased

    private void btnBuyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyMouseReleased
        if (btnBuy.isEnabled()) {
            btnBuy.setEnabled(false);
            btnCancel.setEnabled(false);
            ifPurchaseSuccess.setVisible(true);
        }
    }//GEN-LAST:event_btnBuyMouseReleased

    private void btnPurchaseOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPurchaseOkMouseReleased
            ifPurchaseSuccess.setVisible(false);
            spSummary.setVisible(false);
            ifTickets.setVisible(true);
            btnBuy.setVisible(false);
            btnCancel.setVisible(false);
    }//GEN-LAST:event_btnPurchaseOkMouseReleased

    private void rbDinnerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDinnerMouseReleased
        panelShowMeal.setVisible(true);
        lblSoupText.setText("Sopa de Cenoura");
        lblMeatText.setText("Carne Assada");
        lblFishText.setText("Salmão");
        lblVegetarianText.setText("Massa");
        lblDessertText.setText("Salada de Fruta"); 
    }//GEN-LAST:event_rbDinnerMouseReleased

    private void btnYesCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYesCancelMouseReleased
        if (btnYesCancel.isEnabled()) {
            panelChooseDay.setVisible(false);
            panelShowMeal.setVisible(false);
            btnConfirmMeal.setVisible(false);
            btnCancel.setVisible(false);
            ifTickets.setVisible(false);
            spSummary.setVisible(false);
            btnBuy.setVisible(false);
            ifWarning.setVisible(false);
            btnBuyTicket.setEnabled(true);
            btnCheckBalance.setEnabled(true);
            btnChangePinCode.setEnabled(true);
            btnChangeEmail.setEnabled(true);
            panelWelcome.setVisible(true);
        }
    }//GEN-LAST:event_btnYesCancelMouseReleased

    private void btnNoCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoCancelMouseReleased
        ifWarning.setVisible(false);
        if(panelChooseDay.isVisible()) {
            btnConfirmMeal.setEnabled(false);
        }
        if(rbMeat.isSelected()) {
            btnConfirmMeal.setEnabled(true);
        }
        btnBuy.setEnabled(true);
    }//GEN-LAST:event_btnNoCancelMouseReleased

    private void btnCheckBalanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckBalanceMouseReleased
        if (btnCheckBalance.isEnabled()) {
            panelWelcome.setVisible(false);
            panelCheckBalance.setVisible(true);
            panelChangePinCode.setVisible(false);
            btnCheckBalance.setEnabled(false);
            btnChangePinCode.setEnabled(true);
            btnChangeEmail.setEnabled(true);
        }
    }//GEN-LAST:event_btnCheckBalanceMouseReleased

    private void btnChangePinCodeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePinCodeMouseReleased
        if (btnChangePinCode.isEnabled()) {
            panelWelcome.setVisible(false);
            panelChangePinCode.setVisible(true);
            panelCheckBalance.setVisible(false);
            btnCheckBalance.setEnabled(true);
            btnChangePinCode.setEnabled(false);
            btnChangeEmail.setEnabled(true);
            ifChangePinCodeSuccess.setVisible(false);
            btnValidatePinCode.setEnabled(true);
            btnCancelNewPinCode.setEnabled(true);
            pfCurrentPin.setText(null);
            pfNewPin.setText(null);
            pfConfirmPin.setText(null);
        }
    }//GEN-LAST:event_btnChangePinCodeMouseReleased

    private void btnValidatePinCodeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidatePinCodeMouseReleased
        if(btnValidatePinCode.isEnabled()) {
            ifChangePinCodeSuccess.setVisible(true);
            btnValidatePinCode.setEnabled(false);
            btnCancelNewPinCode.setEnabled(false);
        }
    }//GEN-LAST:event_btnValidatePinCodeMouseReleased

    private void btnCancelNewPinCodeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelNewPinCodeMouseReleased
        if(btnCancelNewPinCode.isEnabled()) {
            ifChangePinCodeSuccess.setVisible(false);
            panelChangePinCode.setVisible(false);
            btnChangePinCode.setEnabled(true);
            panelWelcome.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelNewPinCodeMouseReleased

    private void btnChangeEmailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeEmailMouseReleased
        panelWelcome.setVisible(false);
        panelChangeEmail.setVisible(true);
        panelCheckBalance.setVisible(false);
        panelChangePinCode.setVisible(false);
        btnChangeEmail.setEnabled(false);
        btnCheckBalance.setEnabled(true);
        btnChangePinCode.setEnabled(true);
        ifChangeEmailSuccess.setVisible(false);
        btnValidateEmail.setEnabled(true);
        btnCancelNewEmail.setEnabled(true);
        tfNewMailText.setText(null);
    }//GEN-LAST:event_btnChangeEmailMouseReleased

    private void btnChangeEmailOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeEmailOkMouseReleased
        panelChangeEmail.setVisible(false);
        ifChangeEmailSuccess.setVisible(false);
        btnChangeEmail.setEnabled(true);
    }//GEN-LAST:event_btnChangeEmailOkMouseReleased

    private void btnValidateEmailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValidateEmailMouseReleased
        if(btnValidateEmail.isEnabled()) {
            ifChangeEmailSuccess.setVisible(true);
            btnValidateEmail.setEnabled(false);
            btnCancelNewEmail.setEnabled(false);
        }
    }//GEN-LAST:event_btnValidateEmailMouseReleased

    private void btnCancelNewEmailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelNewEmailMouseReleased
        if(btnCancelNewEmail.isEnabled()) {
            panelChangeEmail.setVisible(false);
            ifChangeEmailSuccess.setVisible(false);
            btnChangeEmail.setEnabled(true);
            panelWelcome.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelNewEmailMouseReleased

    private void btnChangePinCodeSuccessOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePinCodeSuccessOkMouseReleased
        ifChangePinCodeSuccess.setVisible(false);
        panelChangePinCode.setVisible(false);         
        btnChangePinCode.setEnabled(true);
    }//GEN-LAST:event_btnChangePinCodeSuccessOkMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frontend().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDish;
    private javax.swing.ButtonGroup bgTime;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnBuyTicket;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelNewEmail;
    private javax.swing.JButton btnCancelNewPinCode;
    private javax.swing.JButton btnChangeEmail;
    private javax.swing.JButton btnChangeEmailOk;
    private javax.swing.JButton btnChangePinCode;
    private javax.swing.JButton btnChangePinCodeSuccessOk;
    private javax.swing.JButton btnCheckBalance;
    private javax.swing.JButton btnConfirmMeal;
    private javax.swing.JButton btnNoCancel;
    private javax.swing.JButton btnNoTickets;
    private javax.swing.JButton btnPurchaseOk;
    private javax.swing.JButton btnTerminate;
    private javax.swing.JButton btnValidateEmail;
    private javax.swing.JButton btnValidatePinCode;
    private javax.swing.JButton btnYesCancel;
    private javax.swing.JButton btnYesTickets;
    private javax.swing.JComboBox cbDayChoice;
    private javax.swing.JComboBox cbMonthChoice;
    private javax.swing.JComboBox cbYearChoice;
    private javax.swing.JCheckBox chbScholarship;
    private javax.swing.JButton confirm;
    private javax.swing.JInternalFrame ifChangeEmailSuccess;
    private javax.swing.JInternalFrame ifChangePinCodeSuccess;
    private javax.swing.JInternalFrame ifPurchaseSuccess;
    private javax.swing.JInternalFrame ifTickets;
    private javax.swing.JInternalFrame ifWarning;
    private javax.swing.JLabel lbTicketlMealTimeText;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAccountText;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressText;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceText;
    private javax.swing.JLabel lblChangeEmailSuccess;
    private javax.swing.JLabel lblChangePinCodeSuccess1;
    private javax.swing.JLabel lblChangePinCodeSuccess2;
    private javax.swing.JLabel lblChooseDish;
    private javax.swing.JLabel lblConfiirmPin;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblCourseText;
    private javax.swing.JLabel lblCurrentEmail;
    private javax.swing.JLabel lblCurrentEmailText;
    private javax.swing.JLabel lblCurrentPin;
    private javax.swing.JLabel lblDessert;
    private javax.swing.JLabel lblDessertText;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailText;
    private javax.swing.JLabel lblFish;
    private javax.swing.JLabel lblFishText;
    private javax.swing.JLabel lblFrontBK;
    private javax.swing.JLabel lblFrontBK1;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblMeat;
    private javax.swing.JLabel lblMeatText;
    private javax.swing.JLabel lblMoreTickets1;
    private javax.swing.JLabel lblMoreTickets2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameText;
    private javax.swing.JLabel lblNewEmail;
    private javax.swing.JLabel lblNewPin;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneText;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPriceText;
    private javax.swing.JLabel lblPurchaseDate;
    private javax.swing.JLabel lblPurchaseDateText;
    private javax.swing.JLabel lblPurchaseSuccess;
    private javax.swing.JLabel lblScholarship;
    private javax.swing.JLabel lblSoup;
    private javax.swing.JLabel lblSoupText;
    private javax.swing.JLabel lblTicketDessert;
    private javax.swing.JLabel lblTicketDessertText;
    private javax.swing.JLabel lblTicketDish;
    private javax.swing.JLabel lblTicketDishText;
    private javax.swing.JLabel lblTicketMealDate;
    private javax.swing.JLabel lblTicketMealDateText;
    private javax.swing.JLabel lblTicketMealTime;
    private javax.swing.JLabel lblTicketSoup;
    private javax.swing.JLabel lblTicketSoupText;
    private javax.swing.JLabel lblVegetarian;
    private javax.swing.JLabel lblVegetarianText;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JLabel lblWelcome3;
    private javax.swing.JList lisDates;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JLayeredPane lpMeal1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField number;
    private javax.swing.JPanel panelAccount;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelBuyTicket;
    private javax.swing.JPanel panelChangeEmail;
    private javax.swing.JPanel panelChangeEmailFields;
    private javax.swing.JPanel panelChangePinCode;
    private javax.swing.JPanel panelChangePinCodeFields;
    private javax.swing.JPanel panelCheckBalance;
    private javax.swing.JPanel panelChooseDay;
    private javax.swing.JPanel panelMovements;
    private javax.swing.JPanel panelShowMeal;
    private javax.swing.JPanel panelStudent;
    private javax.swing.JPanel panelSummary;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JPasswordField pfConfirmPin;
    private javax.swing.JPasswordField pfCurrentPin;
    private javax.swing.JPasswordField pfNewPin;
    private javax.swing.JPasswordField pinCode;
    private javax.swing.JRadioButton rbDinner;
    private javax.swing.JRadioButton rbFish;
    private javax.swing.JRadioButton rbLunch;
    private javax.swing.JRadioButton rbMeat;
    private javax.swing.JRadioButton rbVegetarian;
    private javax.swing.JSeparator separator;
    private javax.swing.JScrollPane spMovements;
    private javax.swing.JScrollPane spSummary;
    private javax.swing.JTextField tfNewMailText;
    // End of variables declaration//GEN-END:variables
}
